### ISSUE TITLE
Console Spam to Insane Game Slow Down

### ISSUE THREAD

**Issue by Goldenlion5648** [TelepathicGrunt/CommandStructures-Forge#4]
I typed the command /spawnpieces minecraft:village (which spawnpieces does not have intellisense hints BTW) and the game console started spamming this

https://pastebin.com/R2ZYFubX

The game then showed working % 2 and slowly went counted up (After about a minute or two it was at % 30) and I decided to kill the game

**Comment by TelepathicGrunt** [comment]
You were spawning every single village pieces there are. Hence why it was taking a long time to spawn them. Gotta wait it out or be more specific with the command to narrow down to less pieces to spawn. 

Here’s the info on that command: 
![1E8A3082-17E2-472F-A070-DB1C1C95D9CA](https://user-images.githubusercontent.com/40846040/152268526-0b3d5799-4616-40b7-a114-e414e5d53756.jpeg)

It basically takes a resourcelocation that acts as a file path. Then it looks for all nbt pieces under that path. minecraft:village means it looks into data/minecraft/structures/village… and all pieces under that file path is spawned. 

The autocomplete seems to be dying for you for some reason so that’s something I’ll look into.

**Comment by TelepathicGrunt** [comment]
More info on all the command and what the args do can be found on my mod page here: https://www.curseforge.com/minecraft/mc-mods/commandstructures

**Comment by TelepathicGrunt** [comment]
fixed the autocomplete crash in v1.4.3 which is released now. Thank you for reporting that!
