### ISSUE TITLE
Large Jigsaws Overlap

### ISSUE THREAD

**Issue by catter1** [TelepathicGrunt/CommandStructures-Forge#6]
When working with large jigsaw pieces (thanks Carpet mod), the Jigsaws placed with `/spawnpieces` can overlap with each other. See the image below.

(The "chunk border" looking thing on the left is not caused by your mod, that is an intentional part of my structure)

![2024-02-10_19 27 38](https://github.com/TelepathicGrunt/CommandStructures/assets/63272345/225b9a2c-915f-4813-a99b-68b54bf4a1a4)

**Comment by TelepathicGrunt** [comment]
It is because I space out the pieces by 48 based on vanilla's max size.

For maximum speed, I set the structure void over the entire area first.

Then I spawn each template separately from there. So I have no access to the size of the templates initially when clearing out the areas.

Furthermore, if I do dynamically space things out based on template size, it would either make everything spaced out super far even for small pieces. Or I accept and make the grid of pieces no longer a grid. 

Pros and cons for something when breaking the 48 block limit

**Comment by catter1** [comment]
Yeah, the cons are fair. Maybe a solution could be another argument to the command, that overrides the default 48 to whatever spacing the user wants? That way the "dynamic-ness" would only apply if the user specifically says to, in which case they would be okay with everything being spaced out.

(and yes, the real solution is I need to stop using such large Jigsaws :P)

**Comment by TelepathicGrunt** [comment]
v4.3.1 now has spacing argument at end of spawn pieces command
